name: Bbuild APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Get Dependencies
        run: flutter pub get
        working-directory: mobile

      - name: Build APK
        run: flutter build apk --release
        working-directory: mobile

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
